title: UNIST-DA
description: UNIST Data Analytics Lab
# 프로젝트 페이지(하위 경로)용 설정
url: "https://unist-da.github.io"
baseurl: "/DA-LAB-homepage"

theme: mere-blog-theme

paginate: 6
paginate_path: "/page:num"
