title: DA LAB
description: UNIST Data Analytics Lab
url: "https://sieun-00.github.io"
baseurl: "/DA-LAB-homepage"

plugins:
  - jekyll-remote-theme
remote_theme: <테마_소유자>/<테마_저장소>  # ← 정확한 owner/repo로 교체!

paginate: 6
paginate_path: "/page:num"

